print("% This file is automatically generated by ltjlist.lua.")

function inner(a, b, c)
   print("\\ltj@@listing@jpset{" .. a  .. "}{" 
      .. b .. "}{" .. c .. "}")
end
t = {{0x2000, 0xFEFF, "BMP"}, {0x20000, 0x2FFFF, "SIP"}}
for g, v in pairs(t) do
   print("\\message{" .. v[3] .. "}")
   for x = v[1],v[2],128 do
      inner(x, x+127, "\\lst@ProcessJALetter")
   end
end

print("\\message{Hankaku}")
inner(0xFF00, 0xFF60, "\\lst@ProcessJALetter")
inner(0xFF61, 0xFF9F, "\\lst@ProcessJALetterHalf")
inner(0xFFE0, 0xFFE5, "\\lst@ProcessJALetter")

print("\\message{done.}")