print("% This file is automatically generated by ltjlist.lua.")

function inner(a, b, c)
   print("\\ltj@@listing@jpset{" .. a  .. "}{" .. b .. "}")
end
function innerN(a, b, c)
   print("\\ltj@@listing@jpsetN{" .. a  .. "}{" 
      .. b .. "}{" .. c .. "}")
end
k = 256
t = {{0x2000, 0xFEFF, "BMP"}, {0x20000, 0x2FFFF, "SIP"}}
for g, v in pairs(t) do
   print("\\message{" .. v[3] .. "}")
   for x = v[1],v[2],k do
      inner(x, x+k-1, "\\lst@ProcessJALetter")
   end
end

print("\\message{Hankaku}")
innerN(0xFF00, 0xFF60, "\\lst@ProcessJALetter")
innerN(0xFF61, 0xFF9F, "\\lst@ProcessJALetterHalf")
innerN(0xFFE0, 0xFFE5, "\\lst@ProcessJALetter")

print("\\message{done.}")
