ltj.loadlua('luatexja-ucs2aj16.lua')
-- generated by mk_lua.py

function ltj.mk_rml(name, size)
  local f = {}; local g = {}
  f.name = name .. size
  f.fullname = name
  f.filename = ''; f.psname = name
  f.cidinfo = { ordering="Japan1", registry="Adobe",
      supplement=6, usedname="Adobe-Japan1-6.cidmap"}
  f.embedding='no'; f.cache='no'; f.format='opentype'
  f.encodingbytes=2; f.designsize=size
  f.characters = ltj.ucs2aj16_chars
  return f
end

local dr_orig = fonts.define.read
function fonts.define.read(name, size, id)
   local p = utf.find(name, ":") or utf.len(name)+1
   local tmp = utf.sub(name, 1, p-1)
   if tmp == 'psft' then
      local q = utf.find(name, ":",p+1) or utf.len(name)+1
      return ltj.mk_rml(utf.sub(name,p+1,q-1), size)
   else 
      return dr_orig(name, size, id)
   end
end
